name: penread_v1
description: "PenguinRead - An RSVP Speed Reading Web App."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  
  # Routing
  go_router: ^14.2.0
  
  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2
  
  # Forms
  flutter_form_builder: 
  form_builder_validators: 
  form_builder_extra_fields: 
  
  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  
  # Networking & Backend
  dio: ^5.5.0+1
  supabase_flutter: ^2.6.0
  connectivity_plus: ^6.0.4
  
  # Styling
  flex_color_scheme: ^8.0.0 # Upgraded to v8.0.0+ for latest Flutter support
  google_fonts: ^6.2.1
  
  # Utils
  logger: ^2.3.0
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
